name: go
on:
  pull_request: {}

jobs:
  unit:
    name: unit
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: make test

